# Site settings
title: thebestisyettocome
email: sammycheung@me.com
description: a personal space for Cantopop
baseurl: 
url: "http://thebestisyettoco.me"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
